### ISSUE TITLE
Some output data is inconsistent with actual in game date

### ISSUE THREAD

**Issue by David-Melo** [brct-james/captain-of-industry-recipe-parser#1]
First of, thanks for sharing this. Awesome work.
While reviewing the output data, I came upon at least one inconsistency.

![image](https://user-images.githubusercontent.com/1429949/171991418-b24cc3ff-25b4-4797-8b2b-56140f73097d.png)

The Ids.Recipes.CharcoalBurning recipe should have exhaust as an output, but in decompiled_machine_recipes.tsv it doesn't show that as an output.

It's hard to verify if that's the only case, it might apply to other items too. Can't think of an easy way to verify.

Thanks

**Comment by brct-james** [comment]
Thanks for pointing that out. Ill look into why it might be doing that. Recipes are evidently pretty inconsistent in how they are defined. I just noticed I'm completely missing all of the assembler recipes as well 😦

**Comment by brct-james** [comment]
ItsDesm#0283 on the official discord wrote a mod that exports the recipe data more reliably. If they end up sharing a git repo I'll direct users there instead. You can get the json files they generated from the discord if you search for them

**Comment by brct-james** [comment]
Closing issue as project is deprecated, use [this repo](https://github.com/David-Melo/captain-of-data) instead
